//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberSepeti.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public string Baslik { get; set; }
        public string URL { get; set; }
        public string Aciklama { get; set; }
        public string ResimURL { get; set; }
        public int Id { get; set; }
        public bool AktifMi { get; set; }
    }
}
