//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberSepeti.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int Id { get; set; }
        public string Icerik { get; set; }
        public int KullaniciId { get; set; }
        public int HaberId { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
    
        public virtual Haber Haber { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
